// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAccGh87b57sA6Ca_Px9Gl_PFxCBh3S8bA',
    appId: '1:414704277152:web:63240ba02e3d2aed071bc5',
    messagingSenderId: '414704277152',
    projectId: 'whatsapp-14f24',
    authDomain: 'whatsapp-14f24.firebaseapp.com',
    storageBucket: 'whatsapp-14f24.firebasestorage.app',
    measurementId: 'G-59BJGDJBYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuqGIUklh-LvacGIKMpWPfnaOpDfzwEDc',
    appId: '1:414704277152:android:89fe44494161205b071bc5',
    messagingSenderId: '414704277152',
    projectId: 'whatsapp-14f24',
    storageBucket: 'whatsapp-14f24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi2woihdS-vBhIc5oPz5daaghlxghP0jg',
    appId: '1:414704277152:ios:ffd40f0d7523d7f4071bc5',
    messagingSenderId: '414704277152',
    projectId: 'whatsapp-14f24',
    storageBucket: 'whatsapp-14f24.firebasestorage.app',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi2woihdS-vBhIc5oPz5daaghlxghP0jg',
    appId: '1:414704277152:ios:ffd40f0d7523d7f4071bc5',
    messagingSenderId: '414704277152',
    projectId: 'whatsapp-14f24',
    storageBucket: 'whatsapp-14f24.firebasestorage.app',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAccGh87b57sA6Ca_Px9Gl_PFxCBh3S8bA',
    appId: '1:414704277152:web:eeeea11571d91457071bc5',
    messagingSenderId: '414704277152',
    projectId: 'whatsapp-14f24',
    authDomain: 'whatsapp-14f24.firebaseapp.com',
    storageBucket: 'whatsapp-14f24.firebasestorage.app',
    measurementId: 'G-LJ5GXMXR84',
  );
}
